version: 2

before:
  hooks:
    - go generate ./...

builds:
  - id: client
    main: ./cmd/client
    binary: gater
    ldflags:
      - "-s -w -X github.com/cao7113/gater/internal/version.Version={{ .Version }} -X github.com/cao7113/gater/internal/version.Commit={{ .Commit }} -X github.com/cao7113/gater/internal/version.Date={{ .Date }}"
    env:
      - CGO_ENABLED=0
  - id: server
    main: ./cmd/server
    binary: server
    ldflags:
      - "-s -w -X github.com/cao7113/gater/internal/version.Version={{ .Version }} -X github.com/cao7113/gater/internal/version.Commit={{ .Commit }} -X github.com/cao7113/gater/internal/version.Date={{ .Date }}"
    env:
      - CGO_ENABLED=0

archives:
  - id: gater
    builds:
      - client
      - server
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "gater_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native

release:
  replace_existing_artifacts: true
