# https://taskfile.dev/docs/guide
# https://taskfile.dev/reference/templating/
version: '3'
tasks:
  default: |
    go test ./...

  run: |
    go run cmd/server/main.go 
    # http://admin.lab:8080

  cli: |
    go run cmd/client/main.go

  b: |
    go build -o bin/gater ./cmd/server
    go build -o bin/gater-client ./cmd/client
    
  rel.snapshot: |
    goreleaser release --snapshot --clean

  launchd.install: |
    ./scripts/install-macos-launchd.sh

  launchd.uninstall: |
    ./scripts/uninstall-macos-launchd.sh

  gen: |
    go generate ./...

  asset.clean: |
    rm -fr web/dist

  asset.setup: |
    bun add -d tailwindcss @tailwindcss/cli daisyui alpinejs

  setup: |
    # go mod init gater
    go mod tidy
  